language: node_js

node_js:
  - "10.16.0"

services:
  - docker

cache:
  directories:
    - $HOME/.npm-cache
    - $HOME/.npm-prefix
    - $HOME/.npm

jobs:
  include:
    - stage: test
      if: NOT branch = master
      install:
        - set -e
        - npm install
      script:
        - set -e
        - CI=false npm run build
    - stage: release-docker-image
      if: branch = master
      install: true
      provider: script
      script: bash scripts/release-docker-image.sh